name: CI/CD Microservice Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
# Build and test all Microservices 
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
        service: ['customer', 'products', 'shopping']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in microservice
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "^${{ matrix.service }}/"; then
            echo "changes=true" >> $GITHUB_ENV
            echo ${{ matrix.service }}
          else
            echo "changes=false" >> $GITHUB_ENV
          fi
            
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        run: |
          cd ./${{ matrix.service }}
          npm ci
        
      - name: Run Build
        run: |
          cd ./${{ matrix.service }}
          npm run build --if-present
        
      - name: Run Tests
        run: |
          cd ./${{ matrix.service }}
          npm test
        
      - name: Upload build artifact for ${{ matrix.service }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}-build
          path: ./${{ matrix.service }}

# Deploy All Microservice docker images to DockerHub      
  Deploy_To_DockerHub:
    runs-on: ubuntu-latest
    needs: Build
    strategy:
        matrix:
          service: ['customer', 'proxy', 'products', 'shopping']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{matrix.service}}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{github.run_id}}

## Deploy All Microservice docker images to ACR
#  Deploy_To_ACR:
#    name: 'Build and Push to ACR'
#    runs-on: ubuntu-latest
#        
#    defaults:
#      run:
#        shell: bash
#        
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        
#      - name: Docker Login
#        uses: azure/docker-login@v1
#        with:
#          login-server: ${{ secrets.ACR_URL }}
#          username: ${{ secrets.ACR_USERNAME }}
#          password: ${{ secrets.ACR_PASSWORD }}
#        
#      - run: |
#          docker build -t nodejs-app .
#          docker tag nodejs-app ${{ secrets.ACR_URL }}/nodejs-app:${{ github.sha }}
#          docker push ${{ secrets.ACR_URL }}/nodejs-app:${{ github.sha }}
#
## Deploy All Microservice in Web APP
#  Deploy_To_WebApp:
#    permissions:
#      contents: none
#    runs-on: ubuntu-latest
#    needs: Build
#    environment:
#      name: 'Development'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v3
#        with:
#          name: node-app
#
#      - name: 'Deploy to Azure WebApp'
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}









