name: Proxy Microservice Pipeline

on:
  push:
    paths:
      - 'proxy/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env: 
  MICROSERVICE_NAME : 'proxy'

jobs:
    
  Deploy_To_DockerHub:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full commit history, not a shallow clone

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.MICROSERVICE_NAME }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.MICROSERVICE_NAME }}:${{github.run_id}}
          
  