name: Shopping Microservice Pipeline

on:
  push:
    paths:
      - 'shopping/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env: 
  SERVICE_NAME : 'shopping'

jobs:
  # Build and test all Microservices
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install dependencies
        run: |
          cd ./${{ env.SERVICE_NAME }}
          npm ci
        
      - name: Run Build
        run: |
          cd ./${{ env.SERVICE_NAME }}
          npm run build --if-present
        
      - name: Run Tests
        run: |
          cd ./${{ env.SERVICE_NAME }}
          npm test
        
      - name: Upload build artifact for ${{ env.SERVICE_NAME }}
        if: env.changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SERVICE_NAME }}-build
          path: ./${{ env.SERVICE_NAME }}
  